# see http://about.travis-ci.org/docs/user/languages/cpp/ for more hints
language: cpp

# Use container based infrastructure for Travis
sudo: false

# Test against both compilers
compiler:
  - clang
  - gcc

cache:
  directories:
  - $HOME/re

# https://docs.travis-ci.com/user/migrating-from-legacy
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - george-edison55-precise-backports
    packages:
    - build-essential
    - autoconf
    - cmake
    - cmake-data
    - libmysqlclient-dev
    - libssl-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - bash install-re-cached.sh

script:
  - ls -las
  - ls -las $HOME/re
  - export LIBRE_INC=$HOME/re/include
  - export LIBRE_SO=$HOME/re/lib
  - make info
  - make

